# window border
window.active.border.color: #bdccdc
window.inactive.border.color: #bfbedb

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #fd4663

# window titlebar background
window.active.title.bg.color: #bdccdc
window.inactive.title.bg.color: #bfbedb

window.active.label.text.color: #1b1e22
window.inactive.label.text.color: #1b1e22
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #262e36

# window buttons
window.active.button.unpressed.image.color: #1b1e22
window.inactive.button.unpressed.image.color: #1b1e22

# menu
menu.border.color: #1b1e22
menu.items.bg.color: #bdccdc
menu.items.text.color: #1b1e22
menu.items.active.bg.color: #bfbedb
menu.items.active.text.color: #1b1e22
menu.separator.color: #1b1e22
menu.title.bg.color: #bdccdc
menu.title.text.color: #1b1e22

# on screen display (window-cycle dialog)
osd.bg.color: #bdccdc
osd.border.color: #1b1e22
osd.label.text.color: #1b1e22
osd.window-switcher.preview.border.color: #626a72
