# window border
window.active.border.color: #67c5e4
window.inactive.border.color: #5c7ad6

# ToggleKeybinds status indicator
window.active.indicator.toggled-keybind.color: #fd4663

# window titlebar background
window.active.title.bg.color: #67c5e4
window.inactive.title.bg.color: #5c7ad6

window.active.label.text.color: #182225
window.inactive.label.text.color: #0e171a
window.label.text.justify: center

# window button hover overlay
window.button.hover.bg.color: #193143

# window buttons
window.active.button.unpressed.image.color: #182225
window.inactive.button.unpressed.image.color: #182225

# menu
menu.border.color: #182225
menu.items.bg.color: #67c5e4
menu.items.text.color: #182225
menu.items.active.bg.color: #5c7ad6
menu.items.active.text.color: #0e171a
menu.separator.color: #182225
menu.title.bg.color: #67c5e4
menu.title.text.color: #182225

# on screen display (window-cycle dialog)
osd.bg.color: #67c5e4
osd.border.color: #182225
osd.label.text.color: #182225
osd.window-switcher.preview.border.color: #606b70
