[preferred]
# Use GTK for almost everything by default (File Chooser, App Chooser, Settings)
default=gtk

# Explicitly route display capture capabilities to wlroots
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr

# Specific sandboxing portals heavily relied on by Flatpaks and AppImages
org.freedesktop.impl.portal.Background=gtk
org.freedesktop.impl.portal.Documents=gtk
org.freedesktop.impl.portal.OpenURI=gtk
org.freedesktop.impl.portal.Notification=gtk
